INSERT INTO Tag VALUES (0, NULL);
INSERT INTO Tag VALUES (1, ' 1 day or more');
INSERT INTO Tag VALUES (2, ' 15 minutes or less');
INSERT INTO Tag VALUES (3, ' 3 steps or less');
INSERT INTO Tag VALUES (4, ' 30 minutes or less');
INSERT INTO Tag VALUES (5, ' 4 hours or less');
INSERT INTO Tag VALUES (6, ' 5 ingredients or less');
INSERT INTO Tag VALUES (7, ' 60 minutes or less');
INSERT INTO Tag VALUES (8, ' african');
INSERT INTO Tag VALUES (9, ' american');
INSERT INTO Tag VALUES (10, ' amish mennonite');
INSERT INTO Tag VALUES (11, ' appetizers');
INSERT INTO Tag VALUES (12, ' apples');
INSERT INTO Tag VALUES (13, ' argentine');
INSERT INTO Tag VALUES (14, ' asian');
INSERT INTO Tag VALUES (15, ' asparagus');
INSERT INTO Tag VALUES (16, ' australian');
INSERT INTO Tag VALUES (17, ' avocado');
INSERT INTO Tag VALUES (18, ' bacon');
INSERT INTO Tag VALUES (19, ' baja');
INSERT INTO Tag VALUES (20, ' baking');
INSERT INTO Tag VALUES (21, ' bananas');
INSERT INTO Tag VALUES (22, ' bar cookies');
INSERT INTO Tag VALUES (23, ' barbecue');
INSERT INTO Tag VALUES (24, ' bass');
INSERT INTO Tag VALUES (25, ' beans');
INSERT INTO Tag VALUES (26, ' beef');
INSERT INTO Tag VALUES (27, ' beef ribs');
INSERT INTO Tag VALUES (28, ' beef sausage');
INSERT INTO Tag VALUES (29, ' beginner cook');
INSERT INTO Tag VALUES (30, ' berries');
INSERT INTO Tag VALUES (31, ' beverages');
INSERT INTO Tag VALUES (32, ' birthday');
INSERT INTO Tag VALUES (33, ' biscotti');
INSERT INTO Tag VALUES (34, ' bisques cream soups');
INSERT INTO Tag VALUES (35, ' black beans');
INSERT INTO Tag VALUES (36, ' blueberries');
INSERT INTO Tag VALUES (37, ' bread machine');
INSERT INTO Tag VALUES (38, ' breads');
INSERT INTO Tag VALUES (39, ' breakfast');
INSERT INTO Tag VALUES (40, ' broccoli');
INSERT INTO Tag VALUES (41, ' broil');
INSERT INTO Tag VALUES (42, ' brown bag');
INSERT INTO Tag VALUES (43, ' brown rice');
INSERT INTO Tag VALUES (44, ' brownies');
INSERT INTO Tag VALUES (45, ' brunch');
INSERT INTO Tag VALUES (46, ' burgers');
INSERT INTO Tag VALUES (47, ' cajun');
INSERT INTO Tag VALUES (48, ' cake fillings and frostings');
INSERT INTO Tag VALUES (49, ' cakes');
INSERT INTO Tag VALUES (50, ' californian');
INSERT INTO Tag VALUES (51, ' camping');
INSERT INTO Tag VALUES (52, ' canadian');
INSERT INTO Tag VALUES (53, ' candy');
INSERT INTO Tag VALUES (54, ' canning');
INSERT INTO Tag VALUES (55, ' caribbean');
INSERT INTO Tag VALUES (56, ' carrots');
INSERT INTO Tag VALUES (57, ' casseroles');
INSERT INTO Tag VALUES (58, ' catfish');
INSERT INTO Tag VALUES (59, ' cauliflower');
INSERT INTO Tag VALUES (60, ' central american');
INSERT INTO Tag VALUES (61, ' chard');
INSERT INTO Tag VALUES (62, ' cheese');
INSERT INTO Tag VALUES (63, ' cheesecake');
INSERT INTO Tag VALUES (64, ' cherries');
INSERT INTO Tag VALUES (65, ' chick peas garbanzos');
INSERT INTO Tag VALUES (66, ' chicken');
INSERT INTO Tag VALUES (67, ' chicken breasts');
INSERT INTO Tag VALUES (68, ' chicken thighs legs');
INSERT INTO Tag VALUES (69, ' chili');
INSERT INTO Tag VALUES (70, ' chinese');
INSERT INTO Tag VALUES (71, ' chocolate');
INSERT INTO Tag VALUES (72, ' chowders');
INSERT INTO Tag VALUES (73, ' christmas');
INSERT INTO Tag VALUES (74, ' chutneys');
INSERT INTO Tag VALUES (75, ' cinco de mayo');
INSERT INTO Tag VALUES (76, ' citrus');
INSERT INTO Tag VALUES (77, ' cobblers and crisps');
INSERT INTO Tag VALUES (78, ' cocktails');
INSERT INTO Tag VALUES (79, ' coconut');
INSERT INTO Tag VALUES (80, ' coffee cakes');
INSERT INTO Tag VALUES (81, ' colombian');
INSERT INTO Tag VALUES (82, ' comfort food');
INSERT INTO Tag VALUES (83, ' condiments etc');
INSERT INTO Tag VALUES (84, ' cookies and brownies');
INSERT INTO Tag VALUES (85, ' cooking mixes');
INSERT INTO Tag VALUES (86, ' copycat');
INSERT INTO Tag VALUES (87, ' corn');
INSERT INTO Tag VALUES (88, ' course');
INSERT INTO Tag VALUES (89, ' crab');
INSERT INTO Tag VALUES (90, ' crock pot slow cooker');
INSERT INTO Tag VALUES (91, ' crusts pastry dough 2');
INSERT INTO Tag VALUES (92, ' cuisine');
INSERT INTO Tag VALUES (93, ' cupcakes');
INSERT INTO Tag VALUES (94, ' deep fry');
INSERT INTO Tag VALUES (95, ' desserts');
INSERT INTO Tag VALUES (96, ' diabetic');
INSERT INTO Tag VALUES (97, ' dietary');
INSERT INTO Tag VALUES (98, ' dinner party');
INSERT INTO Tag VALUES (99, ' dips');
INSERT INTO Tag VALUES (100, ' drop cookies');
INSERT INTO Tag VALUES (101, ' easter');
INSERT INTO Tag VALUES (102, ' easy');
INSERT INTO Tag VALUES (103, ' egg free');
INSERT INTO Tag VALUES (104, ' eggs');
INSERT INTO Tag VALUES (105, ' eggs dairy');
INSERT INTO Tag VALUES (106, ' elbow macaroni');
INSERT INTO Tag VALUES (107, ' english');
INSERT INTO Tag VALUES (108, ' equipment');
INSERT INTO Tag VALUES (109, ' ethiopian');
INSERT INTO Tag VALUES (110, ' european');
INSERT INTO Tag VALUES (111, ' fall');
INSERT INTO Tag VALUES (112, ' filipino');
INSERT INTO Tag VALUES (113, ' finger food');
INSERT INTO Tag VALUES (114, ' finnish');
INSERT INTO Tag VALUES (115, ' fish');
INSERT INTO Tag VALUES (116, ' food processor blender');
INSERT INTO Tag VALUES (117, ' for 1 or 2');
INSERT INTO Tag VALUES (118, ' for large groups');
INSERT INTO Tag VALUES (119, ' free of something');
INSERT INTO Tag VALUES (120, ' freezer');
INSERT INTO Tag VALUES (121, ' french');
INSERT INTO Tag VALUES (122, ' freshwater fish');
INSERT INTO Tag VALUES (123, ' from scratch');
INSERT INTO Tag VALUES (124, ' frozen desserts');
INSERT INTO Tag VALUES (125, ' fruit');
INSERT INTO Tag VALUES (126, ' garnishes');
INSERT INTO Tag VALUES (127, ' german');
INSERT INTO Tag VALUES (128, ' gifts');
INSERT INTO Tag VALUES (129, ' gluten free');
INSERT INTO Tag VALUES (130, ' grains');
INSERT INTO Tag VALUES (131, ' granola and porridge');
INSERT INTO Tag VALUES (132, ' grapes');
INSERT INTO Tag VALUES (133, ' greek');
INSERT INTO Tag VALUES (134, ' green yellow beans');
INSERT INTO Tag VALUES (135, ' greens');
INSERT INTO Tag VALUES (136, ' grilling');
INSERT INTO Tag VALUES (137, ' ground beef');
INSERT INTO Tag VALUES (138, ' halloween');
INSERT INTO Tag VALUES (139, ' hand formed cookies');
INSERT INTO Tag VALUES (140, ' hanukkah');
INSERT INTO Tag VALUES (141, ' hawaiian');
INSERT INTO Tag VALUES (142, ' healthy');
INSERT INTO Tag VALUES (143, ' healthy 2');
INSERT INTO Tag VALUES (144, ' heirloom historical');
INSERT INTO Tag VALUES (145, ' herb and spice mixes');
INSERT INTO Tag VALUES (146, ' high calcium');
INSERT INTO Tag VALUES (147, ' high fiber');
INSERT INTO Tag VALUES (148, ' high in something');
INSERT INTO Tag VALUES (149, ' high protein');
INSERT INTO Tag VALUES (150, ' holiday event');
INSERT INTO Tag VALUES (151, ' ice cream');
INSERT INTO Tag VALUES (152, ' independence day');
INSERT INTO Tag VALUES (153, ' indian');
INSERT INTO Tag VALUES (154, ' indonesian');
INSERT INTO Tag VALUES (155, ' inexpensive');
INSERT INTO Tag VALUES (156, ' infant baby friendly');
INSERT INTO Tag VALUES (157, ' iranian persian');
INSERT INTO Tag VALUES (158, ' irish');
INSERT INTO Tag VALUES (159, ' italian');
INSERT INTO Tag VALUES (160, ' jams and preserves');
INSERT INTO Tag VALUES (161, ' japanese');
INSERT INTO Tag VALUES (162, ' jellies');
INSERT INTO Tag VALUES (163, ' jewish ashkenazi');
INSERT INTO Tag VALUES (164, ' kid friendly');
INSERT INTO Tag VALUES (165, ' kosher');
INSERT INTO Tag VALUES (166, ' kwanzaa');
INSERT INTO Tag VALUES (167, ' lamb sheep');
INSERT INTO Tag VALUES (168, ' lemon');
INSERT INTO Tag VALUES (169, ' lettuces');
INSERT INTO Tag VALUES (170, ' lime');
INSERT INTO Tag VALUES (171, ' long grain rice');
INSERT INTO Tag VALUES (172, ' low calorie');
INSERT INTO Tag VALUES (173, ' low carb');
INSERT INTO Tag VALUES (174, ' low cholesterol');
INSERT INTO Tag VALUES (175, ' low fat');
INSERT INTO Tag VALUES (176, ' low in something');
INSERT INTO Tag VALUES (177, ' low protein');
INSERT INTO Tag VALUES (178, ' low saturated fat');
INSERT INTO Tag VALUES (179, ' low sodium');
INSERT INTO Tag VALUES (180, ' lunch');
INSERT INTO Tag VALUES (181, ' main dish');
INSERT INTO Tag VALUES (182, ' main ingredient');
INSERT INTO Tag VALUES (183, ' mango');
INSERT INTO Tag VALUES (184, ' mardi gras carnival');
INSERT INTO Tag VALUES (185, ' marinades and rubs');
INSERT INTO Tag VALUES (186, ' mashed potatoes');
INSERT INTO Tag VALUES (187, ' meat');
INSERT INTO Tag VALUES (188, ' meatballs');
INSERT INTO Tag VALUES (189, ' melons');
INSERT INTO Tag VALUES (190, ' mexican');
INSERT INTO Tag VALUES (191, ' microwave');
INSERT INTO Tag VALUES (192, ' middle eastern');
INSERT INTO Tag VALUES (193, ' midwestern');
INSERT INTO Tag VALUES (194, ' mixer');
INSERT INTO Tag VALUES (195, ' moroccan');
INSERT INTO Tag VALUES (196, ' muffins');
INSERT INTO Tag VALUES (197, ' mushrooms');
INSERT INTO Tag VALUES (198, ' native american');
INSERT INTO Tag VALUES (199, ' new years');
INSERT INTO Tag VALUES (200, ' new zealand');
INSERT INTO Tag VALUES (201, ' no cook');
INSERT INTO Tag VALUES (202, ' non alcoholic');
INSERT INTO Tag VALUES (203, ' north american');
INSERT INTO Tag VALUES (204, ' northeastern united states');
INSERT INTO Tag VALUES (205, ' novelty');
INSERT INTO Tag VALUES (206, ' number of servings');
INSERT INTO Tag VALUES (207, ' nut free');
INSERT INTO Tag VALUES (208, ' nuts');
INSERT INTO Tag VALUES (209, ' oamc freezer make ahead');
INSERT INTO Tag VALUES (210, ' occasion');
INSERT INTO Tag VALUES (211, ' omelets and frittatas');
INSERT INTO Tag VALUES (212, ' one dish meal');
INSERT INTO Tag VALUES (213, ' onions');
INSERT INTO Tag VALUES (214, ' ontario');
INSERT INTO Tag VALUES (215, ' orange roughy');
INSERT INTO Tag VALUES (216, ' oranges');
INSERT INTO Tag VALUES (217, ' oven');
INSERT INTO Tag VALUES (218, ' pacific northwest');
INSERT INTO Tag VALUES (219, ' pancakes and waffles');
INSERT INTO Tag VALUES (220, ' papaya');
INSERT INTO Tag VALUES (221, ' passover');
INSERT INTO Tag VALUES (222, ' pasta');
INSERT INTO Tag VALUES (223, ' pasta rice and grains');
INSERT INTO Tag VALUES (224, ' peaches');
INSERT INTO Tag VALUES (225, ' pears');
INSERT INTO Tag VALUES (226, ' pennsylvania dutch');
INSERT INTO Tag VALUES (227, ' peppers');
INSERT INTO Tag VALUES (228, ' pickeral');
INSERT INTO Tag VALUES (229, ' picnic');
INSERT INTO Tag VALUES (230, ' pies');
INSERT INTO Tag VALUES (231, ' pies and tarts');
INSERT INTO Tag VALUES (232, ' pineapple');
INSERT INTO Tag VALUES (233, ' pitted fruit');
INSERT INTO Tag VALUES (234, ' pizza');
INSERT INTO Tag VALUES (235, ' plums');
INSERT INTO Tag VALUES (236, ' polynesian');
INSERT INTO Tag VALUES (237, ' pork');
INSERT INTO Tag VALUES (238, ' pork chops');
INSERT INTO Tag VALUES (239, ' pork loins');
INSERT INTO Tag VALUES (240, ' pork ribs');
INSERT INTO Tag VALUES (241, ' pork sausage');
INSERT INTO Tag VALUES (242, ' potatoes');
INSERT INTO Tag VALUES (243, ' potluck');
INSERT INTO Tag VALUES (244, ' poultry');
INSERT INTO Tag VALUES (245, ' preparation');
INSERT INTO Tag VALUES (246, ' presentation');
INSERT INTO Tag VALUES (247, ' puddings and mousses');
INSERT INTO Tag VALUES (248, ' puerto rican');
INSERT INTO Tag VALUES (249, ' punch');
INSERT INTO Tag VALUES (250, ' quick breads');
INSERT INTO Tag VALUES (251, ' ramadan');
INSERT INTO Tag VALUES (252, ' raspberries');
INSERT INTO Tag VALUES (253, ' ravioli tortellini');
INSERT INTO Tag VALUES (254, ' refrigerator');
INSERT INTO Tag VALUES (255, ' rice');
INSERT INTO Tag VALUES (256, ' roast');
INSERT INTO Tag VALUES (257, ' roast beef');
INSERT INTO Tag VALUES (258, ' rolled cookies');
INSERT INTO Tag VALUES (259, ' rolls biscuits');
INSERT INTO Tag VALUES (260, ' romantic');
INSERT INTO Tag VALUES (261, ' rosh hashana');
INSERT INTO Tag VALUES (262, ' russian');
INSERT INTO Tag VALUES (263, ' salad dressings');
INSERT INTO Tag VALUES (264, ' salads');
INSERT INTO Tag VALUES (265, ' salmon');
INSERT INTO Tag VALUES (266, ' saltwater fish');
INSERT INTO Tag VALUES (267, ' sandwiches');
INSERT INTO Tag VALUES (268, ' sauces');
INSERT INTO Tag VALUES (269, ' saudi arabian');
INSERT INTO Tag VALUES (270, ' savory');
INSERT INTO Tag VALUES (271, ' savory pies');
INSERT INTO Tag VALUES (272, ' savory sauces');
INSERT INTO Tag VALUES (273, ' scandinavian');
INSERT INTO Tag VALUES (274, ' scottish');
INSERT INTO Tag VALUES (275, ' seafood');
INSERT INTO Tag VALUES (276, ' seasonal');
INSERT INTO Tag VALUES (277, ' served cold');
INSERT INTO Tag VALUES (278, ' served hot');
INSERT INTO Tag VALUES (279, ' shakes');
INSERT INTO Tag VALUES (280, ' shellfish');
INSERT INTO Tag VALUES (281, ' short grain rice');
INSERT INTO Tag VALUES (282, ' shrimp');
INSERT INTO Tag VALUES (283, ' side dishes');
INSERT INTO Tag VALUES (284, ' small appliance');
INSERT INTO Tag VALUES (285, ' smoothies');
INSERT INTO Tag VALUES (286, ' snacks');
INSERT INTO Tag VALUES (287, ' soul');
INSERT INTO Tag VALUES (288, ' soups stews');
INSERT INTO Tag VALUES (289, ' sourdough');
INSERT INTO Tag VALUES (290, ' south african');
INSERT INTO Tag VALUES (291, ' south american');
INSERT INTO Tag VALUES (292, ' south west pacific');
INSERT INTO Tag VALUES (293, ' southern united states');
INSERT INTO Tag VALUES (294, ' southwestern united states');
INSERT INTO Tag VALUES (295, ' soy tofu');
INSERT INTO Tag VALUES (296, ' spaghetti');
INSERT INTO Tag VALUES (297, ' spanish');
INSERT INTO Tag VALUES (298, ' spicy');
INSERT INTO Tag VALUES (299, ' spinach');
INSERT INTO Tag VALUES (300, ' spreads');
INSERT INTO Tag VALUES (301, ' spring');
INSERT INTO Tag VALUES (302, ' squash');
INSERT INTO Tag VALUES (303, ' st patricks day');
INSERT INTO Tag VALUES (304, ' steak');
INSERT INTO Tag VALUES (305, ' steam');
INSERT INTO Tag VALUES (306, ' stews');
INSERT INTO Tag VALUES (307, ' stir fry');
INSERT INTO Tag VALUES (308, ' stocks');
INSERT INTO Tag VALUES (309, ' stove top');
INSERT INTO Tag VALUES (310, ' strawberries');
INSERT INTO Tag VALUES (311, ' stuffings dressings');
INSERT INTO Tag VALUES (312, ' summer');
INSERT INTO Tag VALUES (313, ' super bowl');
INSERT INTO Tag VALUES (314, ' superbowl');
INSERT INTO Tag VALUES (315, ' swedish');
INSERT INTO Tag VALUES (316, ' sweet');
INSERT INTO Tag VALUES (317, ' sweet sauces');
INSERT INTO Tag VALUES (318, ' swiss');
INSERT INTO Tag VALUES (319, ' tarts');
INSERT INTO Tag VALUES (320, ' taste mood');
INSERT INTO Tag VALUES (321, ' technique');
INSERT INTO Tag VALUES (322, ' tempeh');
INSERT INTO Tag VALUES (323, ' tex mex');
INSERT INTO Tag VALUES (324, ' thanksgiving');
INSERT INTO Tag VALUES (325, ' time to make');
INSERT INTO Tag VALUES (326, ' to go');
INSERT INTO Tag VALUES (327, ' toddler friendly');
INSERT INTO Tag VALUES (328, ' tomatoes');
INSERT INTO Tag VALUES (329, ' tropical fruit');
INSERT INTO Tag VALUES (330, ' tuna');
INSERT INTO Tag VALUES (331, ' turkey');
INSERT INTO Tag VALUES (332, ' turkey burgers');
INSERT INTO Tag VALUES (333, ' valentines day');
INSERT INTO Tag VALUES (334, ' veal');
INSERT INTO Tag VALUES (335, ' vegan');
INSERT INTO Tag VALUES (336, ' vegetables');
INSERT INTO Tag VALUES (337, ' vegetarian');
INSERT INTO Tag VALUES (338, ' very low carbs');
INSERT INTO Tag VALUES (339, ' vietnamese');
INSERT INTO Tag VALUES (340, ' water bath');
INSERT INTO Tag VALUES (341, ' wedding');
INSERT INTO Tag VALUES (342, ' weeknight');
INSERT INTO Tag VALUES (343, ' welsh');
INSERT INTO Tag VALUES (344, ' white rice');
INSERT INTO Tag VALUES (345, ' whole chicken');
INSERT INTO Tag VALUES (346, ' whole turkey');
INSERT INTO Tag VALUES (347, ' winter');
INSERT INTO Tag VALUES (348, ' yams sweet potatoes');
INSERT INTO Tag VALUES (349, ' yeast');
INSERT INTO Tag VALUES (350, '15 minutes or less');
INSERT INTO Tag VALUES (351, '30 minutes or less');
INSERT INTO Tag VALUES (352, '60 minutes or less');
INSERT INTO Tag VALUES (353, 'bacon');
INSERT INTO Tag VALUES (354, 'course');
INSERT INTO Tag VALUES (355, 'curries');
INSERT INTO Tag VALUES (356, 'danish');
INSERT INTO Tag VALUES (357, 'lactose');
INSERT INTO Tag VALUES (358, NULL);
INSERT INTO Tag VALUES (359, 'time to make');
INSERT INTO Tag VALUES (360, 'weeknight');
